spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: studymongo
      port: 27017
      host: localhost
      auto-index-creation: true
  output:
    ansi:
      enabled: ALWAYS